### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by EvanLovely** [pattern-lab/edition-php-drupal-standard#12]
@dmolsen Could you [enable Travis builds for this repo](https://travis-ci.org/profile/pattern-lab) please? I've got an initial `.travis.yml` file up in [`feature/travis`](https://github.com/pattern-lab/edition-php-drupal-standard/tree/feature/travis). After you enable it, we should just have to push anything to that branch to trigger a build.

**Comment by dmolsen** [comment]
`--no-scripts` is going to make PL generate fail. Maybe we can take advantage of the `env` option to note that this is being run on Travis and quiet the starter kit ask? Does it need to quiet anything else?

**Comment by dmolsen** [comment]
Or I guess i could just check for `$_ENV['COMPOSER_NO_INTERACTION']`. I'll work that into the installer.

**Comment by EvanLovely** [comment]
That'd would be great to have a no interaction mode setup that fired either sensible defaults or options passed in by command line flags. I've been wanting this for using in a Yeoman generator as well. Automatic Travis testing would be great for many of our repos too!

**Comment by EvanLovely** [comment]
The other thing it'd need to quiet would be asking if it should Merge or Replace the StarterKit installs.

**Comment by dmolsen** [comment]
I think we may only be able to shut off and skip prompts in no interaction mode. I also didn't find a way to pass command line arguments through Composer. I didn't look at the actual Composer console class though so maybe there's something there.

The prompts tend to just populate the Config tho so one could always include the defaults in the editions' config.yml to begin with. Interaction mode? User gets to override the default in config.yml. Non-interaction? Just use the default from config.yml. As for starter kits I think you already have the correct solution in travis.yml.

I guess I'll have to add appropriate exit codes too instead of messaging if PL is in Composer's no interaction mode.

**Comment by EvanLovely** [comment]
I made an issue in core for this: https://github.com/pattern-lab/patternlab-php-core/issues/24

**Comment by EvanLovely** [comment]
@dmolsen Could you enable this repo [on Travis](https://travis-ci.org/profile/pattern-lab)? I've got work in [`feature/travis`](https://github.com/pattern-lab/edition-php-drupal-standard/tree/feature/travis) that will use the new changes that involve `--no-interaction` builds. After you enable I can take it from there, or just add a commit to that branch to trigger a test build. Thanks!

**Comment by dmolsen** [comment]
@EvanLovely -

Apologies for dropping the ball on this. This repo has now been enabled on Travis. Let me know if it works out for you.

**Comment by EvanLovely** [comment]
No worries! Working great now! Got a PR up for the Twig Edition: https://github.com/pattern-lab/edition-php-twig-standard/pull/17
